//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlisachcoban
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.LoansItems = new HashSet<LoansItem>();
            this.Reservations = new HashSet<Reservation>();
            this.Authors = new HashSet<Author>();
        }
    
        public long book_id { get; set; }
        public string title { get; set; }
        public Nullable<long> categorie_id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> available { get; set; }
        public string description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<LoansItem> LoansItems { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
