//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlisachcoban
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoansItem
    {
        public long loan_item_id { get; set; }
        public Nullable<long> loan_id { get; set; }
        public Nullable<long> book_id { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
