//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlisachcoban
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public Loan()
        {
            this.LoansItems = new HashSet<LoansItem>();
        }
    
        public long Loan_id { get; set; }
        public Nullable<long> member_id { get; set; }
        public Nullable<System.DateTime> loan_date { get; set; }
        public System.DateTime due_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string status { get; set; }
        public Nullable<long> user_id { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LoansItem> LoansItems { get; set; }
    }
}
