//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlisachcoban
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Loans = new HashSet<Loan>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public long member_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string card_number { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public Nullable<System.DateTime> date_since { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
